/**
 * SQLite implementation of the local journal service contract (C2).
 *
 * Implements the League and Session operations of `LocalJournalService`
 * against the canonical local SQLite database owned by `src/db` (see
 * {@link getDatabase} for the open/migrate/close lifecycle). The remaining
 * contract operations (games, frames, balls, houses, patterns) belong to
 * later packets; each rejects with a descriptive error until implemented.
 *
 * Storage mapping (canonical schema -> C1 domain):
 * - Primary keys are local UUIDs generated by this service
 *   (`crypto.randomUUID()`).
 * - Domain ISO dates (`YYYY-MM-DD`) are stored as INTEGER UTC-midnight
 *   epoch-millisecond timestamps and converted back at the domain boundary.
 * - `Session.laneContext` is stored as a JSON TEXT blob.
 * - `League.houseName` has no canonical column; it is persisted inside the
 *   league `metadata` JSON TEXT column (key `houseName`) and read back from
 *   it. The `metadata` column is a storage detail and is never part of the
 *   C1 domain types.
 * - `LeagueSummary.mostRecentSessionDate` is derived with a `MAX(date)`
 *   aggregate and is never persisted.
 *
 * Behavior:
 * - `getLeague`/`getSession` resolve `null` for unknown ids.
 * - `createLeague`/`createSession` reject on invalid input (a date that is
 *   not `YYYY-MM-DD`) or a failed write (for example a `leagueId` with no
 *   matching league — the canonical FK is enforced with NO ACTION).
 * - `updateLeague`/`updateSession` reject when the entity does not exist;
 *   omitted input fields preserve the stored value, `null` clears it, and a
 *   value sets it.
 * - `removeLeague`/`removeSession` delete by id (idempotent for unknown
 *   ids). Because the canonical FKs are enforced with NO ACTION, deleting a
 *   league that still has sessions (or a session that still has games)
 *   rejects — no cascade, no silent data loss.
 */
import { getDatabase } from '../../db/database';

import type { LocalJournalService } from './local-journal-service';
import type {
  Ball,
  CreateBallInput,
  CreateGameInput,
  CreateHouseInput,
  CreateLeagueInput,
  CreatePatternInput,
  CreateSessionInput,
  Frame,
  FrameInput,
  Game,
  House,
  LaneContext,
  League,
  LeagueSummary,
  ListGamesFilter,
  ListSessionsFilter,
  Pattern,
  Session,
  Uuid,
  UpdateGameInput,
  UpdateLeagueInput,
  UpdateSessionInput,
} from './types';

/** Canonical `leagues` column list (matches the canonical DDL). */
const LEAGUE_COLUMNS =
  'id, name, gamesPerSession, houseId, startDate, endDate, metadata';

/** Canonical `sessions` column list (matches the canonical DDL). */
const SESSION_COLUMNS =
  'id, leagueId, date, weekNumber, houseId, ballId, patternId, notes, laneContext';

/** A `leagues` row as read from SQLite. */
interface LeagueRow {
  id: string;
  name: string;
  gamesPerSession: number | null;
  houseId: string | null;
  startDate: number | null;
  endDate: number | null;
  metadata: string | null;
}

/** A league row plus the derived `MAX(sessions.date)` aggregate. */
interface LeagueSummaryRow extends LeagueRow {
  mostRecentSessionDate: number | null;
}

/** A `sessions` row as read from SQLite. */
interface SessionRow {
  id: string;
  leagueId: string | null;
  date: number;
  weekNumber: number | null;
  houseId: string | null;
  ballId: string | null;
  patternId: string | null;
  notes: string | null;
  laneContext: string | null;
}

/* -------------------------------------------------------------------------- */
/* Storage <-> domain mapping helpers                                          */
/* -------------------------------------------------------------------------- */

/**
 * Domain ISO date (`YYYY-MM-DD`) -> INTEGER storage value: the epoch
 * milliseconds of 00:00:00 UTC on that calendar date.
 */
function isoDateToUtcMs(isoDate: string): number {
  const ms = Date.parse(`${isoDate}T00:00:00Z`);
  if (!Number.isFinite(ms)) {
    throw new Error(`Invalid ISO date (expected YYYY-MM-DD): "${isoDate}"`);
  }
  return ms;
}

/** INTEGER storage value -> domain ISO date (`YYYY-MM-DD`). */
function utcMsToIsoDate(utcMs: number): string {
  return new Date(utcMs).toISOString().slice(0, 10);
}

/**
 * Optional/nullable ISO date input -> INTEGER storage value. `null`/omitted
 * passes through as `null`; a present value is parsed (and may reject).
 */
function isoDateToUtcMsOrNull(
  isoDate: string | null | undefined
): number | null {
  return isoDate === undefined || isoDate === null
    ? null
    : isoDateToUtcMs(isoDate);
}

type JsonRecord = Record<string, unknown>;

/**
 * Parse a JSON TEXT column (`metadata`) into a record. `null`/empty input or
 * an unparseable/non-object value yields an empty record (defensive only:
 * this service is the sole writer of these columns).
 */
function parseJsonRecord(raw: string | null): JsonRecord {
  if (!raw) {
    return {};
  }
  try {
    const parsed: unknown = JSON.parse(raw);
    if (
      parsed === null ||
      typeof parsed !== 'object' ||
      Array.isArray(parsed)
    ) {
      return {};
    }
    return parsed as JsonRecord;
  } catch {
    return {};
  }
}

/** Read the denormalized `houseName` from a parsed league `metadata` record. */
function houseNameFromMetadata(metadata: JsonRecord): string | null {
  const value = metadata.houseName;
  return typeof value === 'string' ? value : null;
}

/** Serialize a `metadata` record back to TEXT (`null` when empty). */
function serializeMetadata(metadata: JsonRecord): string | null {
  return Object.keys(metadata).length === 0 ? null : JSON.stringify(metadata);
}

/**
 * Apply `houseName` update semantics to the stored league `metadata` TEXT:
 * `undefined` preserves, `null` clears, a string sets. Returns the
 * serialized `metadata` value to store.
 */
function applyHouseName(
  currentMetadata: string | null,
  houseName: string | null | undefined
): string | null {
  if (houseName === undefined) {
    return currentMetadata;
  }
  const metadata = parseJsonRecord(currentMetadata);
  if (houseName === null) {
    delete metadata.houseName;
  } else {
    metadata.houseName = houseName;
  }
  return serializeMetadata(metadata);
}

/** Parse the stored `laneContext` JSON TEXT into a `LaneContext` (or null). */
function parseLaneContext(raw: string | null): LaneContext | null {
  if (!raw) {
    return null;
  }
  try {
    const parsed: unknown = JSON.parse(raw);
    return parsed !== null &&
      typeof parsed === 'object' &&
      !Array.isArray(parsed)
      ? (parsed as LaneContext)
      : null;
  } catch {
    return null;
  }
}

function leagueRowToLeague(row: LeagueRow): League {
  return {
    id: row.id,
    name: row.name,
    gamesPerSession: row.gamesPerSession,
    houseId: row.houseId,
    houseName: houseNameFromMetadata(parseJsonRecord(row.metadata)),
    startDate: row.startDate === null ? null : utcMsToIsoDate(row.startDate),
    endDate: row.endDate === null ? null : utcMsToIsoDate(row.endDate),
  };
}

function leagueSummaryRowToLeagueSummary(row: LeagueSummaryRow): LeagueSummary {
  return {
    ...leagueRowToLeague(row),
    mostRecentSessionDate:
      row.mostRecentSessionDate === null
        ? null
        : utcMsToIsoDate(row.mostRecentSessionDate),
  };
}

function sessionRowToSession(row: SessionRow): Session {
  return {
    id: row.id,
    leagueId: row.leagueId,
    date: utcMsToIsoDate(row.date),
    weekNumber: row.weekNumber,
    houseId: row.houseId,
    ballId: row.ballId,
    patternId: row.patternId,
    notes: row.notes,
    laneContext: parseLaneContext(row.laneContext),
  };
}

/**
 * Local UUID generation via the project-supported mechanism
 * (`crypto.randomUUID()`). Primary keys must be canonical UUIDs, so this
 * throws rather than falling back to a non-UUID id.
 */
function newUuid(): Uuid {
  if (
    typeof crypto === 'undefined' ||
    typeof crypto.randomUUID !== 'function'
  ) {
    throw new Error('crypto.randomUUID() is not available');
  }
  return crypto.randomUUID();
}

/**
 * Later-packet (C3+) contract operations. Each rejects until its packet
 * implements it; they exist so this class fully implements
 * `LocalJournalService`.
 */
function notImplemented(operation: string): Promise<never> {
  return Promise.reject(
    new Error(
      `${operation} is not implemented (C2 implements leagues and sessions only)`
    )
  );
}

/* -------------------------------------------------------------------------- */
/* Service                                                                     */
/* -------------------------------------------------------------------------- */

export class SqliteLocalJournalService implements LocalJournalService {
  /* -- Leagues ---------------------------------------------------------- */

  async listLeagues(): Promise<League[]> {
    const db = await getDatabase();
    const rows = await db.getAllAsync<LeagueRow>(
      `SELECT ${LEAGUE_COLUMNS} FROM leagues ORDER BY name COLLATE NOCASE, id`
    );
    return rows.map(leagueRowToLeague);
  }

  async listLeagueSummaries(): Promise<LeagueSummary[]> {
    const db = await getDatabase();
    const rows = await db.getAllAsync<LeagueSummaryRow>(
      `SELECT leagues.id, leagues.name, leagues.gamesPerSession, leagues.houseId,
              leagues.startDate, leagues.endDate, leagues.metadata,
              (SELECT MAX(sessions.date)
                 FROM sessions
                WHERE sessions.leagueId = leagues.id) AS mostRecentSessionDate
         FROM leagues
         ORDER BY leagues.name COLLATE NOCASE, leagues.id`
    );
    return rows.map(leagueSummaryRowToLeagueSummary);
  }

  async getLeague(id: Uuid): Promise<League | null> {
    const db = await getDatabase();
    const row = await db.getFirstAsync<LeagueRow>(
      `SELECT ${LEAGUE_COLUMNS} FROM leagues WHERE id = ?`,
      [id]
    );
    return row === null ? null : leagueRowToLeague(row);
  }

  async createLeague(input: CreateLeagueInput): Promise<League> {
    const db = await getDatabase();
    const id = newUuid();
    await db.runAsync(
      `INSERT INTO leagues
         (id, name, gamesPerSession, houseId, startDate, endDate, metadata)
       VALUES (?, ?, ?, ?, ?, ?, ?)`,
      [
        id,
        input.name,
        input.gamesPerSession ?? null,
        input.houseId ?? null,
        isoDateToUtcMsOrNull(input.startDate),
        isoDateToUtcMsOrNull(input.endDate),
        applyHouseName(null, input.houseName),
      ]
    );
    const row = await db.getFirstAsync<LeagueRow>(
      `SELECT ${LEAGUE_COLUMNS} FROM leagues WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`League not found: ${id}`);
    }
    return leagueRowToLeague(row);
  }

  async updateLeague(id: Uuid, input: UpdateLeagueInput): Promise<League> {
    const db = await getDatabase();
    const current = await db.getFirstAsync<LeagueRow>(
      `SELECT ${LEAGUE_COLUMNS} FROM leagues WHERE id = ?`,
      [id]
    );
    if (current === null) {
      throw new Error(`League not found: ${id}`);
    }

    // Update semantics: an omitted field preserves the stored value, `null`
    // clears it, and a value sets it.
    const gamesPerSession =
      input.gamesPerSession === undefined
        ? current.gamesPerSession
        : input.gamesPerSession;
    const houseId =
      input.houseId === undefined ? current.houseId : input.houseId;
    const startDate =
      input.startDate === undefined
        ? current.startDate
        : isoDateToUtcMsOrNull(input.startDate);
    const endDate =
      input.endDate === undefined
        ? current.endDate
        : isoDateToUtcMsOrNull(input.endDate);

    await db.runAsync(
      `UPDATE leagues
       SET name = ?, gamesPerSession = ?, houseId = ?, startDate = ?, endDate = ?,
           metadata = ?
       WHERE id = ?`,
      [
        input.name,
        gamesPerSession,
        houseId,
        startDate,
        endDate,
        applyHouseName(current.metadata, input.houseName),
        id,
      ]
    );

    const row = await db.getFirstAsync<LeagueRow>(
      `SELECT ${LEAGUE_COLUMNS} FROM leagues WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`League not found: ${id}`);
    }
    return leagueRowToLeague(row);
  }

  async removeLeague(id: Uuid): Promise<void> {
    const db = await getDatabase();
    await db.runAsync('DELETE FROM leagues WHERE id = ?', [id]);
  }

  /* -- Sessions (league or open) --------------------------------------- */

  async listSessions(filter?: ListSessionsFilter): Promise<Session[]> {
    const db = await getDatabase();
    const params: (Uuid | null)[] = [];
    let where = '';
    if (filter !== undefined && filter.leagueId !== undefined) {
      if (filter.leagueId === null) {
        where = ' WHERE leagueId IS NULL';
      } else {
        where = ' WHERE leagueId = ?';
        params.push(filter.leagueId);
      }
    }
    const rows = await db.getAllAsync<SessionRow>(
      `SELECT ${SESSION_COLUMNS} FROM sessions${where} ORDER BY date, id`,
      params
    );
    return rows.map(sessionRowToSession);
  }

  async getSession(id: Uuid): Promise<Session | null> {
    const db = await getDatabase();
    const row = await db.getFirstAsync<SessionRow>(
      `SELECT ${SESSION_COLUMNS} FROM sessions WHERE id = ?`,
      [id]
    );
    return row === null ? null : sessionRowToSession(row);
  }

  async createSession(input: CreateSessionInput): Promise<Session> {
    const db = await getDatabase();
    const id = newUuid();
    const laneContext =
      input.laneContext === undefined || input.laneContext === null
        ? null
        : JSON.stringify(input.laneContext);
    await db.runAsync(
      `INSERT INTO sessions
         (id, leagueId, date, weekNumber, houseId, ballId, patternId, notes,
          laneContext)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        id,
        input.leagueId,
        isoDateToUtcMs(input.date),
        input.weekNumber ?? null,
        input.houseId ?? null,
        input.ballId ?? null,
        input.patternId ?? null,
        input.notes ?? null,
        laneContext,
      ]
    );
    const row = await db.getFirstAsync<SessionRow>(
      `SELECT ${SESSION_COLUMNS} FROM sessions WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`Session not found: ${id}`);
    }
    return sessionRowToSession(row);
  }

  async updateSession(id: Uuid, input: UpdateSessionInput): Promise<Session> {
    const db = await getDatabase();
    const current = await db.getFirstAsync<SessionRow>(
      `SELECT ${SESSION_COLUMNS} FROM sessions WHERE id = ?`,
      [id]
    );
    if (current === null) {
      throw new Error(`Session not found: ${id}`);
    }

    // Update semantics: an omitted field preserves the stored value, `null`
    // clears it, and a value sets it.
    const leagueId =
      input.leagueId === undefined ? current.leagueId : input.leagueId;
    const weekNumber =
      input.weekNumber === undefined ? current.weekNumber : input.weekNumber;
    const houseId =
      input.houseId === undefined ? current.houseId : input.houseId;
    const ballId = input.ballId === undefined ? current.ballId : input.ballId;
    const patternId =
      input.patternId === undefined ? current.patternId : input.patternId;
    const notes = input.notes === undefined ? current.notes : input.notes;
    const laneContext =
      input.laneContext === undefined
        ? current.laneContext
        : input.laneContext === null
          ? null
          : JSON.stringify(input.laneContext);

    await db.runAsync(
      `UPDATE sessions
       SET leagueId = ?, date = ?, weekNumber = ?, houseId = ?, ballId = ?,
           patternId = ?, notes = ?, laneContext = ?
       WHERE id = ?`,
      [
        leagueId,
        isoDateToUtcMs(input.date),
        weekNumber,
        houseId,
        ballId,
        patternId,
        notes,
        laneContext,
        id,
      ]
    );

    const row = await db.getFirstAsync<SessionRow>(
      `SELECT ${SESSION_COLUMNS} FROM sessions WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`Session not found: ${id}`);
    }
    return sessionRowToSession(row);
  }

  async removeSession(id: Uuid): Promise<void> {
    const db = await getDatabase();
    await db.runAsync('DELETE FROM sessions WHERE id = ?', [id]);
  }

  /* -- Games (C3) ------------------------------------------------------ */

  async listGames(_filter?: ListGamesFilter): Promise<Game[]> {
    return notImplemented('listGames');
  }

  async getGame(_id: Uuid): Promise<Game | null> {
    return notImplemented('getGame');
  }

  async createGame(_input: CreateGameInput): Promise<Game> {
    return notImplemented('createGame');
  }

  async updateGame(_id: Uuid, _input: UpdateGameInput): Promise<Game> {
    return notImplemented('updateGame');
  }

  async removeGame(_id: Uuid): Promise<void> {
    return notImplemented('removeGame');
  }

  /* -- Game frames (C3) ------------------------------------------------ */

  async getGameFrames(_gameId: Uuid): Promise<Frame[]> {
    return notImplemented('getGameFrames');
  }

  async replaceGameFrames(_gameId: Uuid, _frames: FrameInput[]): Promise<void> {
    return notImplemented('replaceGameFrames');
  }

  /* -- Reference data: balls (C3) -------------------------------------- */

  async listBalls(): Promise<Ball[]> {
    return notImplemented('listBalls');
  }

  async listRecentBalls(): Promise<Ball[]> {
    return notImplemented('listRecentBalls');
  }

  async createBall(_input: CreateBallInput): Promise<Ball> {
    return notImplemented('createBall');
  }

  /* -- Reference data: houses (C3) ------------------------------------- */

  async listHouses(): Promise<House[]> {
    return notImplemented('listHouses');
  }

  async listRecentHouses(): Promise<House[]> {
    return notImplemented('listRecentHouses');
  }

  async createHouse(_input: CreateHouseInput): Promise<House> {
    return notImplemented('createHouse');
  }

  /* -- Reference data: patterns (C3) ----------------------------------- */

  async listPatterns(): Promise<Pattern[]> {
    return notImplemented('listPatterns');
  }

  async listRecentPatterns(): Promise<Pattern[]> {
    return notImplemented('listRecentPatterns');
  }

  async createPattern(_input: CreatePatternInput): Promise<Pattern> {
    return notImplemented('createPattern');
  }
}
