/**
 * SQLite implementation of the local journal service contract (C2/C3/C4).
 *
 * Implements the League, Session, Ball, House, Pattern, Game, and Frame
 * operations of `LocalJournalService` against the canonical local SQLite
 * database owned by `src/db` (see {@link getDatabase} for the
 * open/migrate/close lifecycle).
 *
 * Storage mapping (canonical schema -> C1 domain):
 * - Primary keys are local UUIDs generated by this service
 *   (`crypto.randomUUID()`).
 * - Domain ISO dates (`YYYY-MM-DD`) are stored as INTEGER UTC-midnight
 *   epoch-millisecond timestamps and converted back at the domain boundary.
 * - `Session.laneContext` and `Game.laneContext` are stored as JSON TEXT
 *   blobs; `Game.ballSwitches` is stored as a JSON TEXT array blob.
 * - A frame persists its full canonical field set: `frameNumber`, the
 *   three roll masks (`roll1Mask`/`roll2Mask`/`roll3Mask`), `ballId`, and
 *   `flags`/`pocket`/`footBoard`/`targetBoard`. There is no packed `pins`
 *   column, no derived frame or cumulative score, and no strike/spare/open
 *   classification stored in the database — scoring is derived on demand
 *   (C5, `getGameScore`) from the stored frame masks and is never
 *   persisted.
 * - `League.houseName` has no canonical column; it is persisted inside the
 *   league `metadata` JSON TEXT column (key `houseName`) and read back from
 *   it. The `metadata` column is a storage detail and is never part of the
 *   C1 domain types.
 * - `LeagueSummary.mostRecentSessionDate` is derived with a `MAX(date)`
 *   aggregate and is never persisted.
 * - Balls, houses, and patterns persist their C1 contract fields only
 *   (`name`/`brand`/`coverstock`, `name`/`location`, `name`/`length`). The
 *   `metadata` column exists in the canonical schema but has no C1 domain
 *   field for these entities, so it is never written to or read from.
 * - `listRecent*` returns the most recently *used* references: the entities
 *   referenced by at least one session — and, for balls and patterns,
 *   referenced by at least one game, because the current app establishes
 *   ball/pattern usage on games as well (a game's house, by contrast,
 *   always comes through its session, so house usage remains session-only),
 *   ordered by the date of the most recent referencing session or game
 *   (id descending as a deterministic tie-break), deduplicated, capped at
 *   ten, and containing only used entities. This is the local projection of
 *   the current app's reference recency semantics; the canonical schema has
 *   no usage table or timestamps on these entities, so "used" is observed
 *   through the referencing rows and "recent" through their dates.
 *
 * Behavior:
 * - `getLeague`/`getSession`/`getGame` resolve `null` for unknown ids.
 * - `createLeague`/`createSession`/`createGame` reject on invalid input (a
 *   date that is not `YYYY-MM-DD`) or a failed write (for example a
 *   `leagueId`/`sessionId` with no matching parent — the canonical FKs are
 *   enforced with NO ACTION).
 * - `createBall`/`createHouse`/`createPattern` persist the supplied
 *   contract fields (absent optional fields become `NULL`) and reject on a
 *   failed write.
 * - `listBalls`/`listHouses`/`listPatterns` return every row of the entity,
 *   ordered by `name` (case-insensitive) then `id`.
 * - `updateLeague`/`updateSession`/`updateGame` reject when the entity does
 *   not exist; omitted input fields preserve the stored value, `null`
 *   clears it, and a value sets it.
 * - `listGames` returns games ordered by `date` then `id`; the optional
 *   filter narrows by `sessionId` or by a league's sessions (the canonical
 *   session -> league hierarchy).
 * - `removeLeague`/`removeSession`/`removeGame` delete by id (idempotent
 *   for unknown ids). Because the canonical FKs are enforced with NO
 *   ACTION, deleting a league that still has sessions, a session that still
 *   has games, or a game that still has frames rejects — no cascade, no
 *   silent data loss.
 * - `getGameFrames` returns a game's frames ordered by `frameNumber`.
 * - `replaceGameFrames` runs in an explicit transaction: it confirms the
 *   game exists, deletes the game's existing frames, and inserts the
 *   replacement set — all-or-nothing, so a failure leaves the previous
 *   frame set untouched.
 */
import { scoreGameFrames } from './game-scoring';
import { getDatabase } from '../../db/database';

import type { LocalJournalService } from './local-journal-service';
import type {
  Ball,
  BallSwitch,
  CreateBallInput,
  CreateGameInput,
  CreateHouseInput,
  CreateLeagueInput,
  CreatePatternInput,
  CreateSessionInput,
  Frame,
  FrameInput,
  Game,
  GameScore,
  House,
  LaneContext,
  League,
  LeagueSummary,
  ListGamesFilter,
  ListSessionsFilter,
  Pattern,
  Session,
  Uuid,
  UpdateGameInput,
  UpdateLeagueInput,
  UpdateSessionInput,
} from './types';

/** Canonical `leagues` column list (matches the canonical DDL). */
const LEAGUE_COLUMNS =
  'id, name, gamesPerSession, houseId, startDate, endDate, metadata';

/** Canonical `sessions` column list (matches the canonical DDL). */
const SESSION_COLUMNS =
  'id, leagueId, date, weekNumber, houseId, ballId, patternId, notes, laneContext';

/** Canonical `games` column list (matches the canonical DDL). */
const GAME_COLUMNS =
  'id, sessionId, date, houseId, ballId, patternId, handicap, notes, laneContext, ballSwitches';

/** Canonical `frames` column list (matches the canonical DDL). */
const FRAME_COLUMNS =
  'id, gameId, frameNumber, roll1Mask, roll2Mask, roll3Mask, ballId, flags, pocket, footBoard, targetBoard';

/** Canonical `balls` column list (matches the canonical DDL). */
const BALL_COLUMNS = 'id, name, brand, coverstock, metadata';

/** Canonical `houses` column list (matches the canonical DDL). */
const HOUSE_COLUMNS = 'id, name, location, metadata';

/** Canonical `patterns` column list (matches the canonical DDL). */
const PATTERN_COLUMNS = 'id, name, length, metadata';

/**
 * Cap on `listRecent*` results, matching the current app's reference
 * "recent" queries (Convex `limit: 10`).
 */
const RECENT_REFERENCE_LIMIT = 10;

/** A `leagues` row as read from SQLite. */
interface LeagueRow {
  id: string;
  name: string;
  gamesPerSession: number | null;
  houseId: string | null;
  startDate: number | null;
  endDate: number | null;
  metadata: string | null;
}

/** A league row plus the derived `MAX(sessions.date)` aggregate. */
interface LeagueSummaryRow extends LeagueRow {
  mostRecentSessionDate: number | null;
}

/** A `sessions` row as read from SQLite. */
interface SessionRow {
  id: string;
  leagueId: string | null;
  date: number;
  weekNumber: number | null;
  houseId: string | null;
  ballId: string | null;
  patternId: string | null;
  notes: string | null;
  laneContext: string | null;
}

/** A `games` row as read from SQLite. */
interface GameRow {
  id: string;
  sessionId: string;
  date: number;
  houseId: string | null;
  ballId: string | null;
  patternId: string | null;
  handicap: number | null;
  notes: string | null;
  laneContext: string | null;
  ballSwitches: string | null;
}

/** A `frames` row as read from SQLite. */
interface FrameRow {
  id: string;
  gameId: string;
  frameNumber: number;
  roll1Mask: number | null;
  roll2Mask: number | null;
  roll3Mask: number | null;
  ballId: string | null;
  flags: number | null;
  pocket: number | null;
  footBoard: number | null;
  targetBoard: number | null;
}

/** A `balls` row as read from SQLite. */
interface BallRow {
  id: string;
  name: string;
  brand: string | null;
  coverstock: string | null;
  metadata: string | null;
}

/** A `houses` row as read from SQLite. */
interface HouseRow {
  id: string;
  name: string;
  location: string | null;
  metadata: string | null;
}

/** A `patterns` row as read from SQLite. */
interface PatternRow {
  id: string;
  name: string;
  length: number | null;
  metadata: string | null;
}

/* -------------------------------------------------------------------------- */
/* Storage <-> domain mapping helpers                                          */
/* -------------------------------------------------------------------------- */

/**
 * Domain ISO date (`YYYY-MM-DD`) -> INTEGER storage value: the epoch
 * milliseconds of 00:00:00 UTC on that calendar date.
 */
function isoDateToUtcMs(isoDate: string): number {
  const ms = Date.parse(`${isoDate}T00:00:00Z`);
  if (!Number.isFinite(ms)) {
    throw new Error(`Invalid ISO date (expected YYYY-MM-DD): "${isoDate}"`);
  }
  return ms;
}

/** INTEGER storage value -> domain ISO date (`YYYY-MM-DD`). */
function utcMsToIsoDate(utcMs: number): string {
  return new Date(utcMs).toISOString().slice(0, 10);
}

/**
 * Optional/nullable ISO date input -> INTEGER storage value. `null`/omitted
 * passes through as `null`; a present value is parsed (and may reject).
 */
function isoDateToUtcMsOrNull(
  isoDate: string | null | undefined
): number | null {
  return isoDate === undefined || isoDate === null
    ? null
    : isoDateToUtcMs(isoDate);
}

type JsonRecord = Record<string, unknown>;

/**
 * Parse a JSON TEXT column (`metadata`) into a record. `null`/empty input or
 * an unparseable/non-object value yields an empty record (defensive only:
 * this service is the sole writer of these columns).
 */
function parseJsonRecord(raw: string | null): JsonRecord {
  if (!raw) {
    return {};
  }
  try {
    const parsed: unknown = JSON.parse(raw);
    if (
      parsed === null ||
      typeof parsed !== 'object' ||
      Array.isArray(parsed)
    ) {
      return {};
    }
    return parsed as JsonRecord;
  } catch {
    return {};
  }
}

/** Read the denormalized `houseName` from a parsed league `metadata` record. */
function houseNameFromMetadata(metadata: JsonRecord): string | null {
  const value = metadata.houseName;
  return typeof value === 'string' ? value : null;
}

/** Serialize a `metadata` record back to TEXT (`null` when empty). */
function serializeMetadata(metadata: JsonRecord): string | null {
  return Object.keys(metadata).length === 0 ? null : JSON.stringify(metadata);
}

/**
 * Apply `houseName` update semantics to the stored league `metadata` TEXT:
 * `undefined` preserves, `null` clears, a string sets. Returns the
 * serialized `metadata` value to store.
 */
function applyHouseName(
  currentMetadata: string | null,
  houseName: string | null | undefined
): string | null {
  if (houseName === undefined) {
    return currentMetadata;
  }
  const metadata = parseJsonRecord(currentMetadata);
  if (houseName === null) {
    delete metadata.houseName;
  } else {
    metadata.houseName = houseName;
  }
  return serializeMetadata(metadata);
}

/** Parse the stored `laneContext` JSON TEXT into a `LaneContext` (or null). */
function parseLaneContext(raw: string | null): LaneContext | null {
  if (!raw) {
    return null;
  }
  try {
    const parsed: unknown = JSON.parse(raw);
    return parsed !== null &&
      typeof parsed === 'object' &&
      !Array.isArray(parsed)
      ? (parsed as LaneContext)
      : null;
  } catch {
    return null;
  }
}

/**
 * Parse the stored `ballSwitches` JSON TEXT into a `BallSwitch[]` (or
 * `null` when the column is NULL or holds no array).
 */
function parseBallSwitches(raw: string | null): BallSwitch[] | null {
  if (!raw) {
    return null;
  }
  try {
    const parsed: unknown = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as BallSwitch[]) : null;
  } catch {
    return null;
  }
}

function leagueRowToLeague(row: LeagueRow): League {
  return {
    id: row.id,
    name: row.name,
    gamesPerSession: row.gamesPerSession,
    houseId: row.houseId,
    houseName: houseNameFromMetadata(parseJsonRecord(row.metadata)),
    startDate: row.startDate === null ? null : utcMsToIsoDate(row.startDate),
    endDate: row.endDate === null ? null : utcMsToIsoDate(row.endDate),
  };
}

function leagueSummaryRowToLeagueSummary(row: LeagueSummaryRow): LeagueSummary {
  return {
    ...leagueRowToLeague(row),
    mostRecentSessionDate:
      row.mostRecentSessionDate === null
        ? null
        : utcMsToIsoDate(row.mostRecentSessionDate),
  };
}

function sessionRowToSession(row: SessionRow): Session {
  return {
    id: row.id,
    leagueId: row.leagueId,
    date: utcMsToIsoDate(row.date),
    weekNumber: row.weekNumber,
    houseId: row.houseId,
    ballId: row.ballId,
    patternId: row.patternId,
    notes: row.notes,
    laneContext: parseLaneContext(row.laneContext),
  };
}

/** Map a `games` row to the C1 `Game` domain. */
function gameRowToGame(row: GameRow): Game {
  return {
    id: row.id,
    sessionId: row.sessionId,
    date: utcMsToIsoDate(row.date),
    houseId: row.houseId,
    ballId: row.ballId,
    patternId: row.patternId,
    handicap: row.handicap,
    notes: row.notes,
    laneContext: parseLaneContext(row.laneContext),
    ballSwitches: parseBallSwitches(row.ballSwitches),
  };
}

/** Map a `frames` row to the C1 `Frame` domain. */
function frameRowToFrame(row: FrameRow): Frame {
  return {
    id: row.id,
    gameId: row.gameId,
    frameNumber: row.frameNumber,
    roll1Mask: row.roll1Mask,
    roll2Mask: row.roll2Mask,
    roll3Mask: row.roll3Mask,
    ballId: row.ballId,
    flags: row.flags,
    pocket: row.pocket,
    footBoard: row.footBoard,
    targetBoard: row.targetBoard,
  };
}

function ballRowToBall(row: BallRow): Ball {
  return {
    id: row.id,
    name: row.name,
    brand: row.brand,
    coverstock: row.coverstock,
  };
}

function houseRowToHouse(row: HouseRow): House {
  return {
    id: row.id,
    name: row.name,
    location: row.location,
  };
}

function patternRowToPattern(row: PatternRow): Pattern {
  return {
    id: row.id,
    name: row.name,
    length: row.length,
  };
}

/**
 * Local UUID generation via the project-supported mechanism
 * (`crypto.randomUUID()`). Primary keys must be canonical UUIDs, so this
 * throws rather than falling back to a non-UUID id.
 */
function newUuid(): Uuid {
  if (
    typeof crypto === 'undefined' ||
    typeof crypto.randomUUID !== 'function'
  ) {
    throw new Error('crypto.randomUUID() is not available');
  }
  return crypto.randomUUID();
}

/**
 * The ids of the most recently used references for one entity kind,
 * derived from the rows that reference the given column: always the
 * sessions that reference it, plus — for `ballId` and `patternId` — the
 * games that reference it, because the current app establishes ball/pattern
 * usage on games as well (a game's house, by contrast, always comes through
 * its session, so house usage remains session-only). Referencing rows are
 * walked in recency order (date descending, then id descending as a
 * deterministic tie-break), deduplicated (the first — i.e. most recent —
 * occurrence of an entity wins), and capped at
 * {@link RECENT_REFERENCE_LIMIT}.
 *
 * The canonical schema has no usage table and no timestamps on balls,
 * houses, or patterns, so "used" is observed through the referencing rows
 * and "recent" through the dates of those rows.
 */
async function recentReferenceIds(
  db: Awaited<ReturnType<typeof getDatabase>>,
  referenceColumn: 'ballId' | 'houseId' | 'patternId'
): Promise<Uuid[]> {
  const usageQueries = [
    `SELECT ${referenceColumn} AS referenceId, date, id
       FROM sessions
      WHERE ${referenceColumn} IS NOT NULL`,
  ];
  if (referenceColumn !== 'houseId') {
    usageQueries.push(
      `SELECT ${referenceColumn} AS referenceId, date, id
         FROM games
        WHERE ${referenceColumn} IS NOT NULL`
    );
  }
  const rows = await db.getAllAsync<{ referenceId: string }>(
    `SELECT referenceId
       FROM (${usageQueries.join(' UNION ALL ')})
      ORDER BY date DESC, id DESC`
  );
  const ids: Uuid[] = [];
  const seen = new Set<string>();
  for (const row of rows) {
    if (seen.has(row.referenceId)) {
      continue;
    }
    seen.add(row.referenceId);
    ids.push(row.referenceId);
    if (ids.length >= RECENT_REFERENCE_LIMIT) {
      break;
    }
  }
  return ids;
}

/* -------------------------------------------------------------------------- */
/* Service                                                                     */
/* -------------------------------------------------------------------------- */

export class SqliteLocalJournalService implements LocalJournalService {
  /* -- Leagues ---------------------------------------------------------- */

  async listLeagues(): Promise<League[]> {
    const db = await getDatabase();
    const rows = await db.getAllAsync<LeagueRow>(
      `SELECT ${LEAGUE_COLUMNS} FROM leagues ORDER BY name COLLATE NOCASE, id`
    );
    return rows.map(leagueRowToLeague);
  }

  async listLeagueSummaries(): Promise<LeagueSummary[]> {
    const db = await getDatabase();
    const rows = await db.getAllAsync<LeagueSummaryRow>(
      `SELECT leagues.id, leagues.name, leagues.gamesPerSession, leagues.houseId,
              leagues.startDate, leagues.endDate, leagues.metadata,
              (SELECT MAX(sessions.date)
                 FROM sessions
                WHERE sessions.leagueId = leagues.id) AS mostRecentSessionDate
         FROM leagues
         ORDER BY leagues.name COLLATE NOCASE, leagues.id`
    );
    return rows.map(leagueSummaryRowToLeagueSummary);
  }

  async getLeague(id: Uuid): Promise<League | null> {
    const db = await getDatabase();
    const row = await db.getFirstAsync<LeagueRow>(
      `SELECT ${LEAGUE_COLUMNS} FROM leagues WHERE id = ?`,
      [id]
    );
    return row === null ? null : leagueRowToLeague(row);
  }

  async createLeague(input: CreateLeagueInput): Promise<League> {
    const db = await getDatabase();
    const id = newUuid();
    await db.runAsync(
      `INSERT INTO leagues
         (id, name, gamesPerSession, houseId, startDate, endDate, metadata)
       VALUES (?, ?, ?, ?, ?, ?, ?)`,
      [
        id,
        input.name,
        input.gamesPerSession ?? null,
        input.houseId ?? null,
        isoDateToUtcMsOrNull(input.startDate),
        isoDateToUtcMsOrNull(input.endDate),
        applyHouseName(null, input.houseName),
      ]
    );
    const row = await db.getFirstAsync<LeagueRow>(
      `SELECT ${LEAGUE_COLUMNS} FROM leagues WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`League not found: ${id}`);
    }
    return leagueRowToLeague(row);
  }

  async updateLeague(id: Uuid, input: UpdateLeagueInput): Promise<League> {
    const db = await getDatabase();
    const current = await db.getFirstAsync<LeagueRow>(
      `SELECT ${LEAGUE_COLUMNS} FROM leagues WHERE id = ?`,
      [id]
    );
    if (current === null) {
      throw new Error(`League not found: ${id}`);
    }

    // Update semantics: an omitted field preserves the stored value, `null`
    // clears it, and a value sets it.
    const gamesPerSession =
      input.gamesPerSession === undefined
        ? current.gamesPerSession
        : input.gamesPerSession;
    const houseId =
      input.houseId === undefined ? current.houseId : input.houseId;
    const startDate =
      input.startDate === undefined
        ? current.startDate
        : isoDateToUtcMsOrNull(input.startDate);
    const endDate =
      input.endDate === undefined
        ? current.endDate
        : isoDateToUtcMsOrNull(input.endDate);

    await db.runAsync(
      `UPDATE leagues
       SET name = ?, gamesPerSession = ?, houseId = ?, startDate = ?, endDate = ?,
           metadata = ?
       WHERE id = ?`,
      [
        input.name,
        gamesPerSession,
        houseId,
        startDate,
        endDate,
        applyHouseName(current.metadata, input.houseName),
        id,
      ]
    );

    const row = await db.getFirstAsync<LeagueRow>(
      `SELECT ${LEAGUE_COLUMNS} FROM leagues WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`League not found: ${id}`);
    }
    return leagueRowToLeague(row);
  }

  async removeLeague(id: Uuid): Promise<void> {
    const db = await getDatabase();
    await db.runAsync('DELETE FROM leagues WHERE id = ?', [id]);
  }

  /* -- Sessions (league or open) --------------------------------------- */

  async listSessions(filter?: ListSessionsFilter): Promise<Session[]> {
    const db = await getDatabase();
    const params: (Uuid | null)[] = [];
    let where = '';
    if (filter !== undefined && filter.leagueId !== undefined) {
      if (filter.leagueId === null) {
        where = ' WHERE leagueId IS NULL';
      } else {
        where = ' WHERE leagueId = ?';
        params.push(filter.leagueId);
      }
    }
    const rows = await db.getAllAsync<SessionRow>(
      `SELECT ${SESSION_COLUMNS} FROM sessions${where} ORDER BY date, id`,
      params
    );
    return rows.map(sessionRowToSession);
  }

  async getSession(id: Uuid): Promise<Session | null> {
    const db = await getDatabase();
    const row = await db.getFirstAsync<SessionRow>(
      `SELECT ${SESSION_COLUMNS} FROM sessions WHERE id = ?`,
      [id]
    );
    return row === null ? null : sessionRowToSession(row);
  }

  async createSession(input: CreateSessionInput): Promise<Session> {
    const db = await getDatabase();
    const id = newUuid();
    const laneContext =
      input.laneContext === undefined || input.laneContext === null
        ? null
        : JSON.stringify(input.laneContext);
    await db.runAsync(
      `INSERT INTO sessions
         (id, leagueId, date, weekNumber, houseId, ballId, patternId, notes,
          laneContext)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        id,
        input.leagueId,
        isoDateToUtcMs(input.date),
        input.weekNumber ?? null,
        input.houseId ?? null,
        input.ballId ?? null,
        input.patternId ?? null,
        input.notes ?? null,
        laneContext,
      ]
    );
    const row = await db.getFirstAsync<SessionRow>(
      `SELECT ${SESSION_COLUMNS} FROM sessions WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`Session not found: ${id}`);
    }
    return sessionRowToSession(row);
  }

  async updateSession(id: Uuid, input: UpdateSessionInput): Promise<Session> {
    const db = await getDatabase();
    const current = await db.getFirstAsync<SessionRow>(
      `SELECT ${SESSION_COLUMNS} FROM sessions WHERE id = ?`,
      [id]
    );
    if (current === null) {
      throw new Error(`Session not found: ${id}`);
    }

    // Update semantics: an omitted field preserves the stored value, `null`
    // clears it, and a value sets it.
    const leagueId =
      input.leagueId === undefined ? current.leagueId : input.leagueId;
    const weekNumber =
      input.weekNumber === undefined ? current.weekNumber : input.weekNumber;
    const houseId =
      input.houseId === undefined ? current.houseId : input.houseId;
    const ballId = input.ballId === undefined ? current.ballId : input.ballId;
    const patternId =
      input.patternId === undefined ? current.patternId : input.patternId;
    const notes = input.notes === undefined ? current.notes : input.notes;
    const laneContext =
      input.laneContext === undefined
        ? current.laneContext
        : input.laneContext === null
          ? null
          : JSON.stringify(input.laneContext);

    await db.runAsync(
      `UPDATE sessions
       SET leagueId = ?, date = ?, weekNumber = ?, houseId = ?, ballId = ?,
           patternId = ?, notes = ?, laneContext = ?
       WHERE id = ?`,
      [
        leagueId,
        isoDateToUtcMs(input.date),
        weekNumber,
        houseId,
        ballId,
        patternId,
        notes,
        laneContext,
        id,
      ]
    );

    const row = await db.getFirstAsync<SessionRow>(
      `SELECT ${SESSION_COLUMNS} FROM sessions WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`Session not found: ${id}`);
    }
    return sessionRowToSession(row);
  }

  async removeSession(id: Uuid): Promise<void> {
    const db = await getDatabase();
    await db.runAsync('DELETE FROM sessions WHERE id = ?', [id]);
  }

  /* -- Games (C4) ------------------------------------------------------ */

  async listGames(filter?: ListGamesFilter): Promise<Game[]> {
    const db = await getDatabase();
    const params: Uuid[] = [];
    const conditions: string[] = [];
    if (filter?.sessionId !== undefined) {
      conditions.push('sessionId = ?');
      params.push(filter.sessionId);
    }
    if (filter?.leagueId !== undefined) {
      // A league's games are the games of the league's sessions (the
      // canonical session -> league hierarchy).
      conditions.push(
        'sessionId IN (SELECT id FROM sessions WHERE leagueId = ?)'
      );
      params.push(filter.leagueId);
    }
    const where =
      conditions.length > 0 ? ` WHERE ${conditions.join(' AND ')}` : '';
    const rows = await db.getAllAsync<GameRow>(
      `SELECT ${GAME_COLUMNS} FROM games${where} ORDER BY date, id`,
      params
    );
    return rows.map(gameRowToGame);
  }

  async getGame(id: Uuid): Promise<Game | null> {
    const db = await getDatabase();
    const row = await db.getFirstAsync<GameRow>(
      `SELECT ${GAME_COLUMNS} FROM games WHERE id = ?`,
      [id]
    );
    return row === null ? null : gameRowToGame(row);
  }

  async createGame(input: CreateGameInput): Promise<Game> {
    const db = await getDatabase();
    const id = newUuid();
    const laneContext =
      input.laneContext === undefined || input.laneContext === null
        ? null
        : JSON.stringify(input.laneContext);
    const ballSwitches =
      input.ballSwitches === undefined || input.ballSwitches === null
        ? null
        : JSON.stringify(input.ballSwitches);
    await db.runAsync(
      `INSERT INTO games
         (id, sessionId, date, houseId, ballId, patternId, handicap, notes,
          laneContext, ballSwitches)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        id,
        input.sessionId,
        isoDateToUtcMs(input.date),
        input.houseId ?? null,
        input.ballId ?? null,
        input.patternId ?? null,
        input.handicap ?? null,
        input.notes ?? null,
        laneContext,
        ballSwitches,
      ]
    );
    const row = await db.getFirstAsync<GameRow>(
      `SELECT ${GAME_COLUMNS} FROM games WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`Game not found: ${id}`);
    }
    return gameRowToGame(row);
  }

  async updateGame(id: Uuid, input: UpdateGameInput): Promise<Game> {
    const db = await getDatabase();
    const current = await db.getFirstAsync<GameRow>(
      `SELECT ${GAME_COLUMNS} FROM games WHERE id = ?`,
      [id]
    );
    if (current === null) {
      throw new Error(`Game not found: ${id}`);
    }

    // Update semantics: an omitted field preserves the stored value, `null`
    // clears it, and a value sets it.
    const houseId =
      input.houseId === undefined ? current.houseId : input.houseId;
    const ballId = input.ballId === undefined ? current.ballId : input.ballId;
    const patternId =
      input.patternId === undefined ? current.patternId : input.patternId;
    const handicap =
      input.handicap === undefined ? current.handicap : input.handicap;
    const notes = input.notes === undefined ? current.notes : input.notes;
    const laneContext =
      input.laneContext === undefined
        ? current.laneContext
        : input.laneContext === null
          ? null
          : JSON.stringify(input.laneContext);
    const ballSwitches =
      input.ballSwitches === undefined
        ? current.ballSwitches
        : input.ballSwitches === null
          ? null
          : JSON.stringify(input.ballSwitches);

    await db.runAsync(
      `UPDATE games
       SET date = ?, houseId = ?, ballId = ?, patternId = ?, handicap = ?,
           notes = ?, laneContext = ?, ballSwitches = ?
       WHERE id = ?`,
      [
        isoDateToUtcMs(input.date),
        houseId,
        ballId,
        patternId,
        handicap,
        notes,
        laneContext,
        ballSwitches,
        id,
      ]
    );

    const row = await db.getFirstAsync<GameRow>(
      `SELECT ${GAME_COLUMNS} FROM games WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`Game not found: ${id}`);
    }
    return gameRowToGame(row);
  }

  async removeGame(id: Uuid): Promise<void> {
    const db = await getDatabase();
    await db.runAsync('DELETE FROM games WHERE id = ?', [id]);
  }

  /* -- Game frames (C4) ----------------------------------------------- */

  async getGameFrames(gameId: Uuid): Promise<Frame[]> {
    const db = await getDatabase();
    const rows = await db.getAllAsync<FrameRow>(
      `SELECT ${FRAME_COLUMNS} FROM frames
        WHERE gameId = ?
      ORDER BY frameNumber, id`,
      [gameId]
    );
    return rows.map(frameRowToFrame);
  }

  async replaceGameFrames(gameId: Uuid, frames: FrameInput[]): Promise<void> {
    const db = await getDatabase();

    // Contract validation before touching the database: the current app's
    // replacement path accepts a `frameNumber` per frame; no bowling-rule
    // (contiguity, roll range) validation is applied here.
    for (let index = 0; index < frames.length; index += 1) {
      const frameNumber = frames[index].frameNumber;
      if (typeof frameNumber !== 'number' || !Number.isFinite(frameNumber)) {
        throw new Error(
          `frames[${index}].frameNumber must be a finite number (got ${String(
            frameNumber
          )})`
        );
      }
    }

    // Explicit transaction: confirm the game, delete the existing frames,
    // and insert the replacement set — all-or-nothing.
    await db.withTransactionAsync(async () => {
      const game = await db.getFirstAsync<{ id: Uuid }>(
        'SELECT id FROM games WHERE id = ?',
        [gameId]
      );
      if (game === null) {
        throw new Error(`Game not found: ${gameId}`);
      }
      await db.runAsync('DELETE FROM frames WHERE gameId = ?', [gameId]);
      for (const frame of frames) {
        const frameId = newUuid();
        await db.runAsync(
          `INSERT INTO frames
             (id, gameId, frameNumber, roll1Mask, roll2Mask, roll3Mask,
              ballId, flags, pocket, footBoard, targetBoard)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
          [
            frameId,
            gameId,
            frame.frameNumber,
            frame.roll1Mask ?? null,
            frame.roll2Mask ?? null,
            frame.roll3Mask ?? null,
            frame.ballId ?? null,
            frame.flags ?? null,
            frame.pocket ?? null,
            frame.footBoard ?? null,
            frame.targetBoard ?? null,
          ]
        );
      }
    });
  }

  /* -- Derived game scoring (C5) ---------------------------------------- */

  async getGameScore(gameId: Uuid): Promise<GameScore | null> {
    const game = await this.getGame(gameId);
    if (game === null) {
      return null;
    }

    const frames = await this.getGameFrames(gameId);
    return scoreGameFrames(frames);
  }

  /* -- Reference data: balls ------------------------------------------- */

  async listBalls(): Promise<Ball[]> {
    const db = await getDatabase();
    const rows = await db.getAllAsync<BallRow>(
      `SELECT ${BALL_COLUMNS} FROM balls ORDER BY name COLLATE NOCASE, id`
    );
    return rows.map(ballRowToBall);
  }

  async listRecentBalls(): Promise<Ball[]> {
    const db = await getDatabase();
    const ids = await recentReferenceIds(db, 'ballId');
    if (ids.length === 0) {
      return [];
    }
    const rows = await db.getAllAsync<BallRow>(
      `SELECT ${BALL_COLUMNS} FROM balls
        WHERE id IN (${ids.map(() => '?').join(', ')})`,
      ids
    );
    const byId = new Map<string, BallRow>(rows.map((row) => [row.id, row]));
    return ids
      .map((id) => byId.get(id))
      .filter((row): row is BallRow => row !== undefined)
      .map(ballRowToBall);
  }

  async createBall(input: CreateBallInput): Promise<Ball> {
    const db = await getDatabase();
    const id = newUuid();
    await db.runAsync(
      'INSERT INTO balls (id, name, brand, coverstock) VALUES (?, ?, ?, ?)',
      [id, input.name, input.brand ?? null, input.coverstock ?? null]
    );
    const row = await db.getFirstAsync<BallRow>(
      `SELECT ${BALL_COLUMNS} FROM balls WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`Ball not found: ${id}`);
    }
    return ballRowToBall(row);
  }

  /* -- Reference data: houses ------------------------------------------ */

  async listHouses(): Promise<House[]> {
    const db = await getDatabase();
    const rows = await db.getAllAsync<HouseRow>(
      `SELECT ${HOUSE_COLUMNS} FROM houses ORDER BY name COLLATE NOCASE, id`
    );
    return rows.map(houseRowToHouse);
  }

  async listRecentHouses(): Promise<House[]> {
    const db = await getDatabase();
    const ids = await recentReferenceIds(db, 'houseId');
    if (ids.length === 0) {
      return [];
    }
    const rows = await db.getAllAsync<HouseRow>(
      `SELECT ${HOUSE_COLUMNS} FROM houses
        WHERE id IN (${ids.map(() => '?').join(', ')})`,
      ids
    );
    const byId = new Map<string, HouseRow>(rows.map((row) => [row.id, row]));
    return ids
      .map((id) => byId.get(id))
      .filter((row): row is HouseRow => row !== undefined)
      .map(houseRowToHouse);
  }

  async createHouse(input: CreateHouseInput): Promise<House> {
    const db = await getDatabase();
    const id = newUuid();
    await db.runAsync(
      'INSERT INTO houses (id, name, location) VALUES (?, ?, ?)',
      [id, input.name, input.location ?? null]
    );
    const row = await db.getFirstAsync<HouseRow>(
      `SELECT ${HOUSE_COLUMNS} FROM houses WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`House not found: ${id}`);
    }
    return houseRowToHouse(row);
  }

  /* -- Reference data: patterns ---------------------------------------- */

  async listPatterns(): Promise<Pattern[]> {
    const db = await getDatabase();
    const rows = await db.getAllAsync<PatternRow>(
      `SELECT ${PATTERN_COLUMNS} FROM patterns ORDER BY name COLLATE NOCASE, id`
    );
    return rows.map(patternRowToPattern);
  }

  async listRecentPatterns(): Promise<Pattern[]> {
    const db = await getDatabase();
    const ids = await recentReferenceIds(db, 'patternId');
    if (ids.length === 0) {
      return [];
    }
    const rows = await db.getAllAsync<PatternRow>(
      `SELECT ${PATTERN_COLUMNS} FROM patterns
        WHERE id IN (${ids.map(() => '?').join(', ')})`,
      ids
    );
    const byId = new Map<string, PatternRow>(rows.map((row) => [row.id, row]));
    return ids
      .map((id) => byId.get(id))
      .filter((row): row is PatternRow => row !== undefined)
      .map(patternRowToPattern);
  }

  async createPattern(input: CreatePatternInput): Promise<Pattern> {
    const db = await getDatabase();
    const id = newUuid();
    await db.runAsync(
      'INSERT INTO patterns (id, name, length) VALUES (?, ?, ?)',
      [id, input.name, input.length ?? null]
    );
    const row = await db.getFirstAsync<PatternRow>(
      `SELECT ${PATTERN_COLUMNS} FROM patterns WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`Pattern not found: ${id}`);
    }
    return patternRowToPattern(row);
  }
}
