/**
 * SQLite implementation of the local journal service contract (C2/C3).
 *
 * Implements the League, Session, Ball, House, and Pattern operations of
 * `LocalJournalService` against the canonical local SQLite database owned
 * by `src/db` (see {@link getDatabase} for the open/migrate/close
 * lifecycle). The remaining contract operations (games, frames) belong to
 * packet C4; each rejects with a descriptive error until implemented.
 *
 * Storage mapping (canonical schema -> C1 domain):
 * - Primary keys are local UUIDs generated by this service
 *   (`crypto.randomUUID()`).
 * - Domain ISO dates (`YYYY-MM-DD`) are stored as INTEGER UTC-midnight
 *   epoch-millisecond timestamps and converted back at the domain boundary.
 * - `Session.laneContext` is stored as a JSON TEXT blob.
 * - `League.houseName` has no canonical column; it is persisted inside the
 *   league `metadata` JSON TEXT column (key `houseName`) and read back from
 *   it. The `metadata` column is a storage detail and is never part of the
 *   C1 domain types.
 * - `LeagueSummary.mostRecentSessionDate` is derived with a `MAX(date)`
 *   aggregate and is never persisted.
 * - Balls, houses, and patterns persist their C1 contract fields only
 *   (`name`/`brand`/`coverstock`, `name`/`location`, `name`/`length`). The
 *   `metadata` column exists in the canonical schema but has no C1 domain
 *   field for these entities, so it is never written to or read from.
 * - `listRecent*` returns the most recently *used* references: the entities
 *   referenced by at least one session, ordered by the date of the most
 *   recent referencing session (session id descending as a deterministic
 *   tie-break), deduplicated, capped at ten, and containing only used
 *   entities. This is the local projection of the current app's reference
 *   recency semantics; the canonical schema has no usage table or
 *   timestamps on these entities, so "used" is observed through the
 *   sessions that reference an entity and "recent" through session dates.
 *
 * Behavior:
 * - `getLeague`/`getSession` resolve `null` for unknown ids.
 * - `createLeague`/`createSession` reject on invalid input (a date that is
 *   not `YYYY-MM-DD`) or a failed write (for example a `leagueId` with no
 *   matching league — the canonical FK is enforced with NO ACTION).
 * - `createBall`/`createHouse`/`createPattern` persist the supplied
 *   contract fields (absent optional fields become `NULL`) and reject on a
 *   failed write.
 * - `listBalls`/`listHouses`/`listPatterns` return every row of the entity,
 *   ordered by `name` (case-insensitive) then `id`.
 * - `updateLeague`/`updateSession` reject when the entity does not exist;
 *   omitted input fields preserve the stored value, `null` clears it, and a
 *   value sets it.
 * - `removeLeague`/`removeSession` delete by id (idempotent for unknown
 *   ids). Because the canonical FKs are enforced with NO ACTION, deleting a
 *   league that still has sessions (or a session that still has games)
 *   rejects — no cascade, no silent data loss.
 */
import { getDatabase } from '../../db/database';

import type { LocalJournalService } from './local-journal-service';
import type {
  Ball,
  CreateBallInput,
  CreateGameInput,
  CreateHouseInput,
  CreateLeagueInput,
  CreatePatternInput,
  CreateSessionInput,
  Frame,
  FrameInput,
  Game,
  House,
  LaneContext,
  League,
  LeagueSummary,
  ListGamesFilter,
  ListSessionsFilter,
  Pattern,
  Session,
  Uuid,
  UpdateGameInput,
  UpdateLeagueInput,
  UpdateSessionInput,
} from './types';

/** Canonical `leagues` column list (matches the canonical DDL). */
const LEAGUE_COLUMNS =
  'id, name, gamesPerSession, houseId, startDate, endDate, metadata';

/** Canonical `sessions` column list (matches the canonical DDL). */
const SESSION_COLUMNS =
  'id, leagueId, date, weekNumber, houseId, ballId, patternId, notes, laneContext';

/** Canonical `balls` column list (matches the canonical DDL). */
const BALL_COLUMNS = 'id, name, brand, coverstock, metadata';

/** Canonical `houses` column list (matches the canonical DDL). */
const HOUSE_COLUMNS = 'id, name, location, metadata';

/** Canonical `patterns` column list (matches the canonical DDL). */
const PATTERN_COLUMNS = 'id, name, length, metadata';

/**
 * Cap on `listRecent*` results, matching the current app's reference
 * "recent" queries (Convex `limit: 10`).
 */
const RECENT_REFERENCE_LIMIT = 10;

/** A `leagues` row as read from SQLite. */
interface LeagueRow {
  id: string;
  name: string;
  gamesPerSession: number | null;
  houseId: string | null;
  startDate: number | null;
  endDate: number | null;
  metadata: string | null;
}

/** A league row plus the derived `MAX(sessions.date)` aggregate. */
interface LeagueSummaryRow extends LeagueRow {
  mostRecentSessionDate: number | null;
}

/** A `sessions` row as read from SQLite. */
interface SessionRow {
  id: string;
  leagueId: string | null;
  date: number;
  weekNumber: number | null;
  houseId: string | null;
  ballId: string | null;
  patternId: string | null;
  notes: string | null;
  laneContext: string | null;
}

/** A `balls` row as read from SQLite. */
interface BallRow {
  id: string;
  name: string;
  brand: string | null;
  coverstock: string | null;
  metadata: string | null;
}

/** A `houses` row as read from SQLite. */
interface HouseRow {
  id: string;
  name: string;
  location: string | null;
  metadata: string | null;
}

/** A `patterns` row as read from SQLite. */
interface PatternRow {
  id: string;
  name: string;
  length: number | null;
  metadata: string | null;
}

/* -------------------------------------------------------------------------- */
/* Storage <-> domain mapping helpers                                          */
/* -------------------------------------------------------------------------- */

/**
 * Domain ISO date (`YYYY-MM-DD`) -> INTEGER storage value: the epoch
 * milliseconds of 00:00:00 UTC on that calendar date.
 */
function isoDateToUtcMs(isoDate: string): number {
  const ms = Date.parse(`${isoDate}T00:00:00Z`);
  if (!Number.isFinite(ms)) {
    throw new Error(`Invalid ISO date (expected YYYY-MM-DD): "${isoDate}"`);
  }
  return ms;
}

/** INTEGER storage value -> domain ISO date (`YYYY-MM-DD`). */
function utcMsToIsoDate(utcMs: number): string {
  return new Date(utcMs).toISOString().slice(0, 10);
}

/**
 * Optional/nullable ISO date input -> INTEGER storage value. `null`/omitted
 * passes through as `null`; a present value is parsed (and may reject).
 */
function isoDateToUtcMsOrNull(
  isoDate: string | null | undefined
): number | null {
  return isoDate === undefined || isoDate === null
    ? null
    : isoDateToUtcMs(isoDate);
}

type JsonRecord = Record<string, unknown>;

/**
 * Parse a JSON TEXT column (`metadata`) into a record. `null`/empty input or
 * an unparseable/non-object value yields an empty record (defensive only:
 * this service is the sole writer of these columns).
 */
function parseJsonRecord(raw: string | null): JsonRecord {
  if (!raw) {
    return {};
  }
  try {
    const parsed: unknown = JSON.parse(raw);
    if (
      parsed === null ||
      typeof parsed !== 'object' ||
      Array.isArray(parsed)
    ) {
      return {};
    }
    return parsed as JsonRecord;
  } catch {
    return {};
  }
}

/** Read the denormalized `houseName` from a parsed league `metadata` record. */
function houseNameFromMetadata(metadata: JsonRecord): string | null {
  const value = metadata.houseName;
  return typeof value === 'string' ? value : null;
}

/** Serialize a `metadata` record back to TEXT (`null` when empty). */
function serializeMetadata(metadata: JsonRecord): string | null {
  return Object.keys(metadata).length === 0 ? null : JSON.stringify(metadata);
}

/**
 * Apply `houseName` update semantics to the stored league `metadata` TEXT:
 * `undefined` preserves, `null` clears, a string sets. Returns the
 * serialized `metadata` value to store.
 */
function applyHouseName(
  currentMetadata: string | null,
  houseName: string | null | undefined
): string | null {
  if (houseName === undefined) {
    return currentMetadata;
  }
  const metadata = parseJsonRecord(currentMetadata);
  if (houseName === null) {
    delete metadata.houseName;
  } else {
    metadata.houseName = houseName;
  }
  return serializeMetadata(metadata);
}

/** Parse the stored `laneContext` JSON TEXT into a `LaneContext` (or null). */
function parseLaneContext(raw: string | null): LaneContext | null {
  if (!raw) {
    return null;
  }
  try {
    const parsed: unknown = JSON.parse(raw);
    return parsed !== null &&
      typeof parsed === 'object' &&
      !Array.isArray(parsed)
      ? (parsed as LaneContext)
      : null;
  } catch {
    return null;
  }
}

function leagueRowToLeague(row: LeagueRow): League {
  return {
    id: row.id,
    name: row.name,
    gamesPerSession: row.gamesPerSession,
    houseId: row.houseId,
    houseName: houseNameFromMetadata(parseJsonRecord(row.metadata)),
    startDate: row.startDate === null ? null : utcMsToIsoDate(row.startDate),
    endDate: row.endDate === null ? null : utcMsToIsoDate(row.endDate),
  };
}

function leagueSummaryRowToLeagueSummary(row: LeagueSummaryRow): LeagueSummary {
  return {
    ...leagueRowToLeague(row),
    mostRecentSessionDate:
      row.mostRecentSessionDate === null
        ? null
        : utcMsToIsoDate(row.mostRecentSessionDate),
  };
}

function sessionRowToSession(row: SessionRow): Session {
  return {
    id: row.id,
    leagueId: row.leagueId,
    date: utcMsToIsoDate(row.date),
    weekNumber: row.weekNumber,
    houseId: row.houseId,
    ballId: row.ballId,
    patternId: row.patternId,
    notes: row.notes,
    laneContext: parseLaneContext(row.laneContext),
  };
}

function ballRowToBall(row: BallRow): Ball {
  return {
    id: row.id,
    name: row.name,
    brand: row.brand,
    coverstock: row.coverstock,
  };
}

function houseRowToHouse(row: HouseRow): House {
  return {
    id: row.id,
    name: row.name,
    location: row.location,
  };
}

function patternRowToPattern(row: PatternRow): Pattern {
  return {
    id: row.id,
    name: row.name,
    length: row.length,
  };
}

/**
 * Local UUID generation via the project-supported mechanism
 * (`crypto.randomUUID()`). Primary keys must be canonical UUIDs, so this
 * throws rather than falling back to a non-UUID id.
 */
function newUuid(): Uuid {
  if (
    typeof crypto === 'undefined' ||
    typeof crypto.randomUUID !== 'function'
  ) {
    throw new Error('crypto.randomUUID() is not available');
  }
  return crypto.randomUUID();
}

/**
 * The ids of the most recently used references for one entity, derived from
 * `sessions`: sessions that reference the given column are walked in
 * recency order (session date descending, then session id descending as a
 * deterministic tie-break), deduplicated (the first — i.e. most recent —
 * occurrence of an entity wins), and capped at
 * {@link RECENT_REFERENCE_LIMIT}.
 *
 * The canonical schema has no usage table and no timestamps on balls,
 * houses, or patterns, so "used" is observed through the sessions that
 * reference an entity and "recent" through the dates of those sessions.
 */
async function recentReferenceIds(
  db: Awaited<ReturnType<typeof getDatabase>>,
  referenceColumn: 'ballId' | 'houseId' | 'patternId'
): Promise<Uuid[]> {
  const rows = await db.getAllAsync<{ referenceId: string }>(
    `SELECT ${referenceColumn} AS referenceId
       FROM sessions
      WHERE ${referenceColumn} IS NOT NULL
      ORDER BY date DESC, id DESC`
  );
  const ids: Uuid[] = [];
  const seen = new Set<string>();
  for (const row of rows) {
    if (seen.has(row.referenceId)) {
      continue;
    }
    seen.add(row.referenceId);
    ids.push(row.referenceId);
    if (ids.length >= RECENT_REFERENCE_LIMIT) {
      break;
    }
  }
  return ids;
}

/**
 * Later-packet (C4) contract operations. Each rejects until its packet
 * implements it; they exist so this class fully implements
 * `LocalJournalService`.
 */
function notImplemented(operation: string): Promise<never> {
  return Promise.reject(
    new Error(
      `${operation} is not implemented (C4 implements games and game frames)`
    )
  );
}

/* -------------------------------------------------------------------------- */
/* Service                                                                     */
/* -------------------------------------------------------------------------- */

export class SqliteLocalJournalService implements LocalJournalService {
  /* -- Leagues ---------------------------------------------------------- */

  async listLeagues(): Promise<League[]> {
    const db = await getDatabase();
    const rows = await db.getAllAsync<LeagueRow>(
      `SELECT ${LEAGUE_COLUMNS} FROM leagues ORDER BY name COLLATE NOCASE, id`
    );
    return rows.map(leagueRowToLeague);
  }

  async listLeagueSummaries(): Promise<LeagueSummary[]> {
    const db = await getDatabase();
    const rows = await db.getAllAsync<LeagueSummaryRow>(
      `SELECT leagues.id, leagues.name, leagues.gamesPerSession, leagues.houseId,
              leagues.startDate, leagues.endDate, leagues.metadata,
              (SELECT MAX(sessions.date)
                 FROM sessions
                WHERE sessions.leagueId = leagues.id) AS mostRecentSessionDate
         FROM leagues
         ORDER BY leagues.name COLLATE NOCASE, leagues.id`
    );
    return rows.map(leagueSummaryRowToLeagueSummary);
  }

  async getLeague(id: Uuid): Promise<League | null> {
    const db = await getDatabase();
    const row = await db.getFirstAsync<LeagueRow>(
      `SELECT ${LEAGUE_COLUMNS} FROM leagues WHERE id = ?`,
      [id]
    );
    return row === null ? null : leagueRowToLeague(row);
  }

  async createLeague(input: CreateLeagueInput): Promise<League> {
    const db = await getDatabase();
    const id = newUuid();
    await db.runAsync(
      `INSERT INTO leagues
         (id, name, gamesPerSession, houseId, startDate, endDate, metadata)
       VALUES (?, ?, ?, ?, ?, ?, ?)`,
      [
        id,
        input.name,
        input.gamesPerSession ?? null,
        input.houseId ?? null,
        isoDateToUtcMsOrNull(input.startDate),
        isoDateToUtcMsOrNull(input.endDate),
        applyHouseName(null, input.houseName),
      ]
    );
    const row = await db.getFirstAsync<LeagueRow>(
      `SELECT ${LEAGUE_COLUMNS} FROM leagues WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`League not found: ${id}`);
    }
    return leagueRowToLeague(row);
  }

  async updateLeague(id: Uuid, input: UpdateLeagueInput): Promise<League> {
    const db = await getDatabase();
    const current = await db.getFirstAsync<LeagueRow>(
      `SELECT ${LEAGUE_COLUMNS} FROM leagues WHERE id = ?`,
      [id]
    );
    if (current === null) {
      throw new Error(`League not found: ${id}`);
    }

    // Update semantics: an omitted field preserves the stored value, `null`
    // clears it, and a value sets it.
    const gamesPerSession =
      input.gamesPerSession === undefined
        ? current.gamesPerSession
        : input.gamesPerSession;
    const houseId =
      input.houseId === undefined ? current.houseId : input.houseId;
    const startDate =
      input.startDate === undefined
        ? current.startDate
        : isoDateToUtcMsOrNull(input.startDate);
    const endDate =
      input.endDate === undefined
        ? current.endDate
        : isoDateToUtcMsOrNull(input.endDate);

    await db.runAsync(
      `UPDATE leagues
       SET name = ?, gamesPerSession = ?, houseId = ?, startDate = ?, endDate = ?,
           metadata = ?
       WHERE id = ?`,
      [
        input.name,
        gamesPerSession,
        houseId,
        startDate,
        endDate,
        applyHouseName(current.metadata, input.houseName),
        id,
      ]
    );

    const row = await db.getFirstAsync<LeagueRow>(
      `SELECT ${LEAGUE_COLUMNS} FROM leagues WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`League not found: ${id}`);
    }
    return leagueRowToLeague(row);
  }

  async removeLeague(id: Uuid): Promise<void> {
    const db = await getDatabase();
    await db.runAsync('DELETE FROM leagues WHERE id = ?', [id]);
  }

  /* -- Sessions (league or open) --------------------------------------- */

  async listSessions(filter?: ListSessionsFilter): Promise<Session[]> {
    const db = await getDatabase();
    const params: (Uuid | null)[] = [];
    let where = '';
    if (filter !== undefined && filter.leagueId !== undefined) {
      if (filter.leagueId === null) {
        where = ' WHERE leagueId IS NULL';
      } else {
        where = ' WHERE leagueId = ?';
        params.push(filter.leagueId);
      }
    }
    const rows = await db.getAllAsync<SessionRow>(
      `SELECT ${SESSION_COLUMNS} FROM sessions${where} ORDER BY date, id`,
      params
    );
    return rows.map(sessionRowToSession);
  }

  async getSession(id: Uuid): Promise<Session | null> {
    const db = await getDatabase();
    const row = await db.getFirstAsync<SessionRow>(
      `SELECT ${SESSION_COLUMNS} FROM sessions WHERE id = ?`,
      [id]
    );
    return row === null ? null : sessionRowToSession(row);
  }

  async createSession(input: CreateSessionInput): Promise<Session> {
    const db = await getDatabase();
    const id = newUuid();
    const laneContext =
      input.laneContext === undefined || input.laneContext === null
        ? null
        : JSON.stringify(input.laneContext);
    await db.runAsync(
      `INSERT INTO sessions
         (id, leagueId, date, weekNumber, houseId, ballId, patternId, notes,
          laneContext)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        id,
        input.leagueId,
        isoDateToUtcMs(input.date),
        input.weekNumber ?? null,
        input.houseId ?? null,
        input.ballId ?? null,
        input.patternId ?? null,
        input.notes ?? null,
        laneContext,
      ]
    );
    const row = await db.getFirstAsync<SessionRow>(
      `SELECT ${SESSION_COLUMNS} FROM sessions WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`Session not found: ${id}`);
    }
    return sessionRowToSession(row);
  }

  async updateSession(id: Uuid, input: UpdateSessionInput): Promise<Session> {
    const db = await getDatabase();
    const current = await db.getFirstAsync<SessionRow>(
      `SELECT ${SESSION_COLUMNS} FROM sessions WHERE id = ?`,
      [id]
    );
    if (current === null) {
      throw new Error(`Session not found: ${id}`);
    }

    // Update semantics: an omitted field preserves the stored value, `null`
    // clears it, and a value sets it.
    const leagueId =
      input.leagueId === undefined ? current.leagueId : input.leagueId;
    const weekNumber =
      input.weekNumber === undefined ? current.weekNumber : input.weekNumber;
    const houseId =
      input.houseId === undefined ? current.houseId : input.houseId;
    const ballId = input.ballId === undefined ? current.ballId : input.ballId;
    const patternId =
      input.patternId === undefined ? current.patternId : input.patternId;
    const notes = input.notes === undefined ? current.notes : input.notes;
    const laneContext =
      input.laneContext === undefined
        ? current.laneContext
        : input.laneContext === null
          ? null
          : JSON.stringify(input.laneContext);

    await db.runAsync(
      `UPDATE sessions
       SET leagueId = ?, date = ?, weekNumber = ?, houseId = ?, ballId = ?,
           patternId = ?, notes = ?, laneContext = ?
       WHERE id = ?`,
      [
        leagueId,
        isoDateToUtcMs(input.date),
        weekNumber,
        houseId,
        ballId,
        patternId,
        notes,
        laneContext,
        id,
      ]
    );

    const row = await db.getFirstAsync<SessionRow>(
      `SELECT ${SESSION_COLUMNS} FROM sessions WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`Session not found: ${id}`);
    }
    return sessionRowToSession(row);
  }

  async removeSession(id: Uuid): Promise<void> {
    const db = await getDatabase();
    await db.runAsync('DELETE FROM sessions WHERE id = ?', [id]);
  }

  /* -- Games (C4) ------------------------------------------------------ */

  async listGames(_filter?: ListGamesFilter): Promise<Game[]> {
    return notImplemented('listGames');
  }

  async getGame(_id: Uuid): Promise<Game | null> {
    return notImplemented('getGame');
  }

  async createGame(_input: CreateGameInput): Promise<Game> {
    return notImplemented('createGame');
  }

  async updateGame(_id: Uuid, _input: UpdateGameInput): Promise<Game> {
    return notImplemented('updateGame');
  }

  async removeGame(_id: Uuid): Promise<void> {
    return notImplemented('removeGame');
  }

  /* -- Game frames (C4) ----------------------------------------------- */

  async getGameFrames(_gameId: Uuid): Promise<Frame[]> {
    return notImplemented('getGameFrames');
  }

  async replaceGameFrames(_gameId: Uuid, _frames: FrameInput[]): Promise<void> {
    return notImplemented('replaceGameFrames');
  }

  /* -- Reference data: balls ------------------------------------------- */

  async listBalls(): Promise<Ball[]> {
    const db = await getDatabase();
    const rows = await db.getAllAsync<BallRow>(
      `SELECT ${BALL_COLUMNS} FROM balls ORDER BY name COLLATE NOCASE, id`
    );
    return rows.map(ballRowToBall);
  }

  async listRecentBalls(): Promise<Ball[]> {
    const db = await getDatabase();
    const ids = await recentReferenceIds(db, 'ballId');
    if (ids.length === 0) {
      return [];
    }
    const rows = await db.getAllAsync<BallRow>(
      `SELECT ${BALL_COLUMNS} FROM balls
        WHERE id IN (${ids.map(() => '?').join(', ')})`,
      ids
    );
    const byId = new Map<string, BallRow>(rows.map((row) => [row.id, row]));
    return ids
      .map((id) => byId.get(id))
      .filter((row): row is BallRow => row !== undefined)
      .map(ballRowToBall);
  }

  async createBall(input: CreateBallInput): Promise<Ball> {
    const db = await getDatabase();
    const id = newUuid();
    await db.runAsync(
      'INSERT INTO balls (id, name, brand, coverstock) VALUES (?, ?, ?, ?)',
      [id, input.name, input.brand ?? null, input.coverstock ?? null]
    );
    const row = await db.getFirstAsync<BallRow>(
      `SELECT ${BALL_COLUMNS} FROM balls WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`Ball not found: ${id}`);
    }
    return ballRowToBall(row);
  }

  /* -- Reference data: houses ------------------------------------------ */

  async listHouses(): Promise<House[]> {
    const db = await getDatabase();
    const rows = await db.getAllAsync<HouseRow>(
      `SELECT ${HOUSE_COLUMNS} FROM houses ORDER BY name COLLATE NOCASE, id`
    );
    return rows.map(houseRowToHouse);
  }

  async listRecentHouses(): Promise<House[]> {
    const db = await getDatabase();
    const ids = await recentReferenceIds(db, 'houseId');
    if (ids.length === 0) {
      return [];
    }
    const rows = await db.getAllAsync<HouseRow>(
      `SELECT ${HOUSE_COLUMNS} FROM houses
        WHERE id IN (${ids.map(() => '?').join(', ')})`,
      ids
    );
    const byId = new Map<string, HouseRow>(rows.map((row) => [row.id, row]));
    return ids
      .map((id) => byId.get(id))
      .filter((row): row is HouseRow => row !== undefined)
      .map(houseRowToHouse);
  }

  async createHouse(input: CreateHouseInput): Promise<House> {
    const db = await getDatabase();
    const id = newUuid();
    await db.runAsync(
      'INSERT INTO houses (id, name, location) VALUES (?, ?, ?)',
      [id, input.name, input.location ?? null]
    );
    const row = await db.getFirstAsync<HouseRow>(
      `SELECT ${HOUSE_COLUMNS} FROM houses WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`House not found: ${id}`);
    }
    return houseRowToHouse(row);
  }

  /* -- Reference data: patterns ---------------------------------------- */

  async listPatterns(): Promise<Pattern[]> {
    const db = await getDatabase();
    const rows = await db.getAllAsync<PatternRow>(
      `SELECT ${PATTERN_COLUMNS} FROM patterns ORDER BY name COLLATE NOCASE, id`
    );
    return rows.map(patternRowToPattern);
  }

  async listRecentPatterns(): Promise<Pattern[]> {
    const db = await getDatabase();
    const ids = await recentReferenceIds(db, 'patternId');
    if (ids.length === 0) {
      return [];
    }
    const rows = await db.getAllAsync<PatternRow>(
      `SELECT ${PATTERN_COLUMNS} FROM patterns
        WHERE id IN (${ids.map(() => '?').join(', ')})`,
      ids
    );
    const byId = new Map<string, PatternRow>(rows.map((row) => [row.id, row]));
    return ids
      .map((id) => byId.get(id))
      .filter((row): row is PatternRow => row !== undefined)
      .map(patternRowToPattern);
  }

  async createPattern(input: CreatePatternInput): Promise<Pattern> {
    const db = await getDatabase();
    const id = newUuid();
    await db.runAsync(
      'INSERT INTO patterns (id, name, length) VALUES (?, ?, ?)',
      [id, input.name, input.length ?? null]
    );
    const row = await db.getFirstAsync<PatternRow>(
      `SELECT ${PATTERN_COLUMNS} FROM patterns WHERE id = ?`,
      [id]
    );
    if (row === null) {
      throw new Error(`Pattern not found: ${id}`);
    }
    return patternRowToPattern(row);
  }
}
