// Auto-generated by scripts/generate-build-info.mjs
// Do not edit manually - this file is regenerated on each build
// Generated: 2026-04-17T20:06:25Z

export const buildInfo = {
  version: '1.0.0',
  gitSha: '1ffd7b5',
  buildTime: '2026-04-17T20:06:25Z',
} as const;
