// Auto-generated by scripts/generate-build-info.mjs
// Do not edit manually - this file is regenerated on each build
// Generated: 2026-09-12T04:53:42Z

export const buildInfo = {
  version: '1.0.0',
  gitSha: 'e91cb0c',
  buildTime: '2026-09-12T04:53:42Z',
} as const;
