import {
  framesListByGameQuery,
  framesReplaceForGameMutation,
  importsApplyPostImportRefinementMutation,
  importsGetImportStatusQuery,
  importsSqliteSnapshotMutation,
  importsStartImportMutation,
  gamesCreateMutation,
  gamesGetByIdQuery,
  gamesListBySessionQuery,
  gamesUpdateMutation,
  leaguesCreateMutation,
  leaguesListQuery,
  sessionsCreateMutation,
  sessionsListByLeagueQuery,
} from '@/convex/functions';

export const convexJournalService = {
  listLeagues: leaguesListQuery,
  createLeague: leaguesCreateMutation,
  listSessionsByLeague: sessionsListByLeagueQuery,
  createSession: sessionsCreateMutation,
  listGamesBySession: gamesListBySessionQuery,
  getGameById: gamesGetByIdQuery,
  createGame: gamesCreateMutation,
  updateGame: gamesUpdateMutation,
  listFramesByGame: framesListByGameQuery,
  replaceFramesForGame: framesReplaceForGameMutation,
  applyPostImportRefinement: importsApplyPostImportRefinementMutation,
  importSqliteSnapshot: importsSqliteSnapshotMutation,
  startImport: importsStartImportMutation,
  getImportStatus: importsGetImportStatusQuery,
} as const;
