import {
  ballsCreateMutation,
  ballsListQuery,
  ballsListRecentQuery,
  framesListByGameQuery,
  framesReplaceForGameMutation,
  importsApplyPostImportRefinementMutation,
  importsGetImportStatusQuery,
  importsSqliteSnapshotMutation,
  importsStartImportMutation,
  gamesCreateMutation,
  gamesRemoveMutation,
  gamesGetByIdQuery,
  gamesListBySessionQuery,
  gamesUpdateMutation,
  housesCreateMutation,
  housesListQuery,
  housesListRecentQuery,
  leaguesCreateMutation,
  leaguesRemoveMutation,
  leaguesListQuery,
  leaguesUpdateMutation,
  patternsCreateMutation,
  patternsListQuery,
  patternsListRecentQuery,
  sessionsCreateMutation,
  sessionsRemoveMutation,
  sessionsListByLeagueQuery,
  sessionsUpdateMutation,
} from '@/convex/functions';

export const convexJournalService = {
  listBalls: ballsListQuery,
  listRecentBalls: ballsListRecentQuery,
  createBall: ballsCreateMutation,
  listPatterns: patternsListQuery,
  listRecentPatterns: patternsListRecentQuery,
  createPattern: patternsCreateMutation,
  listHouses: housesListQuery,
  listRecentHouses: housesListRecentQuery,
  createHouse: housesCreateMutation,
  listLeagues: leaguesListQuery,
  createLeague: leaguesCreateMutation,
  updateLeague: leaguesUpdateMutation,
  removeLeague: leaguesRemoveMutation,
  listSessionsByLeague: sessionsListByLeagueQuery,
  createSession: sessionsCreateMutation,
  updateSession: sessionsUpdateMutation,
  removeSession: sessionsRemoveMutation,
  listGamesBySession: gamesListBySessionQuery,
  getGameById: gamesGetByIdQuery,
  createGame: gamesCreateMutation,
  updateGame: gamesUpdateMutation,
  removeGame: gamesRemoveMutation,
  listFramesByGame: framesListByGameQuery,
  replaceFramesForGame: framesReplaceForGameMutation,
  applyPostImportRefinement: importsApplyPostImportRefinementMutation,
  importSqliteSnapshot: importsSqliteSnapshotMutation,
  startImport: importsStartImportMutation,
  getImportStatus: importsGetImportStatusQuery,
} as const;
